version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - backend
    restart: always

networks:
  backend:
