version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:1.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/docker/nginx/html:/usr/share/nginx/html
      - /home/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker/nginx/conf.d:/etc/nginx/conf.d
      - /home/docker/nginx/cert:/etc/nginx/cert
      - /home/docker/nginx/other:/etc/nginx/other
    networks:
      - backend
    restart: always

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "36379:6379"
    networks:
      - backend
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "33306:3306"
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - /home/docker/mysql/data:/var/lib/mysql
    networks:
      - backend
    restart: always

  winter-dashboard-service:
    container_name: winter-dashboard-service
    image: ccr.ccs.tencentyun.com/winter-studio/winter-dashboard:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=winter-dashboard
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  backend:
