spring:
  profiles:
    default: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #开发环境打开，兼容springfox
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:winter-dashboard}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

knife4j:
  enable: true
  documents:
    -
      group: 1.0版本
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    enableFooterCustom: true
    footerCustomContent: Winter Dashboard
    enableDebug: true
    enableOpenApi: true
    enableGroup: true
  cors: false
  production: false
