# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'

    - name: Build and Push
      run: |
        mvn -B -N -DskipTests=true install
        mvn -B -pl web -DskipTests=true deploy -Ddocker.username=${{ secrets.DEPLOY_DOCKER_USERNAME }} -Ddocker.password=${{ secrets.DEPLOY_DOCKER_PASSWORD }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPOLY_REMOTE_HOST }}
        port: ${{ secrets.DEPOLY_REMOTE_PORT }}
        username: ${{ secrets.DEPOLY_REMOTE_USER }}
        key: ${{ secrets.DEPOLY_SSH_PRIVATE_KEY  }}
        script: ${{ secrets.DEPOLY_SCRIPT }}
